### ISSUE TITLE
Module not found: Error: Can't resolve 'hexer'

### ISSUE THREAD

**Issue by reintroducing** [uber/bufrw#65]
We're seeing this error when we're npm installing https://github.com/jaegertracing/jaeger-client-node in our project through CI. It looks like this was fixed in https://github.com/uber/bufrw/commit/f9118655d8c23a8db23a83c064f772afaf19ae50 but I don't think a new version was ever published to npm with those updates as when we `npm install bufrw` it does not have `hexer` in the dependencies list in `package.json`. Could you please publish the updates to npm so we can get this fixed? 

I know that this project seems to be stale at 3 years old without any action, but I'm really surprised nobody has brought this up over that time span. Not sure why we'd be the only ones running into this, but would really appreciate a publish of a new version to get it fixed.

**Comment by Tchoupinax** [comment]
Same problem here with webpack, any change ? :)

**Comment by kriskowal** [comment]
I’ve published a release with the fix on master.
